'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
'
Namespace FQC
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="FQCSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class FQC
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendFQCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendSubFQCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DelFQCOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.BarCodeScan.My.MySettings.Default.BarCodeScan_FQC_FQC
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendFQCCompleted As SendFQCCompletedEventHandler
        
        '''<remarks/>
        Public Event SendSubFQCCompleted As SendSubFQCCompletedEventHandler
        
        '''<remarks/>
        Public Event DelFQCCompleted As DelFQCCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFQC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendFQC(ByVal model As SendFQCModel) As BizResultOfSendFQCResultModel
            Dim results() As Object = Me.Invoke("SendFQC", New Object() {model})
            Return CType(results(0),BizResultOfSendFQCResultModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendFQCAsync(ByVal model As SendFQCModel)
            Me.SendFQCAsync(model, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendFQCAsync(ByVal model As SendFQCModel, ByVal userState As Object)
            If (Me.SendFQCOperationCompleted Is Nothing) Then
                Me.SendFQCOperationCompleted = AddressOf Me.OnSendFQCOperationCompleted
            End If
            Me.InvokeAsync("SendFQC", New Object() {model}, Me.SendFQCOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendFQCOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendFQCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendFQCCompleted(Me, New SendFQCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSubFQC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendSubFQC(ByVal model As SendFQCModel) As BizResultOfSendFQCResultModel
            Dim results() As Object = Me.Invoke("SendSubFQC", New Object() {model})
            Return CType(results(0),BizResultOfSendFQCResultModel)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendSubFQCAsync(ByVal model As SendFQCModel)
            Me.SendSubFQCAsync(model, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendSubFQCAsync(ByVal model As SendFQCModel, ByVal userState As Object)
            If (Me.SendSubFQCOperationCompleted Is Nothing) Then
                Me.SendSubFQCOperationCompleted = AddressOf Me.OnSendSubFQCOperationCompleted
            End If
            Me.InvokeAsync("SendSubFQC", New Object() {model}, Me.SendSubFQCOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendSubFQCOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendSubFQCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendSubFQCCompleted(Me, New SendSubFQCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DelFQC", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function DelFQC(ByVal model As DelFQCModel) As BizResult
            Dim results() As Object = Me.Invoke("DelFQC", New Object() {model})
            Return CType(results(0),BizResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DelFQCAsync(ByVal model As DelFQCModel)
            Me.DelFQCAsync(model, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DelFQCAsync(ByVal model As DelFQCModel, ByVal userState As Object)
            If (Me.DelFQCOperationCompleted Is Nothing) Then
                Me.DelFQCOperationCompleted = AddressOf Me.OnDelFQCOperationCompleted
            End If
            Me.InvokeAsync("DelFQC", New Object() {model}, Me.DelFQCOperationCompleted, userState)
        End Sub
        
        Private Sub OnDelFQCOperationCompleted(ByVal arg As Object)
            If (Not (Me.DelFQCCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DelFQCCompleted(Me, New DelFQCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendFQCModel
        
        Private lineField As String
        
        Private workOrderCodeField As String
        
        Private remarkField As String
        
        Private storageQuantityField As Single
        
        Private biaoQianTimeField As System.Nullable(Of Date)
        
        Private producDateField As System.Nullable(Of Date)
        
        Private biaoQianWeekField As String
        
        Private userCodeField As String
        
        '''<remarks/>
        Public Property Line() As String
            Get
                Return Me.lineField
            End Get
            Set
                Me.lineField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property WorkOrderCode() As String
            Get
                Return Me.workOrderCodeField
            End Get
            Set
                Me.workOrderCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Remark() As String
            Get
                Return Me.remarkField
            End Get
            Set
                Me.remarkField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StorageQuantity() As Single
            Get
                Return Me.storageQuantityField
            End Get
            Set
                Me.storageQuantityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property BiaoQianTime() As System.Nullable(Of Date)
            Get
                Return Me.biaoQianTimeField
            End Get
            Set
                Me.biaoQianTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property ProducDate() As System.Nullable(Of Date)
            Get
                Return Me.producDateField
            End Get
            Set
                Me.producDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BiaoQianWeek() As String
            Get
                Return Me.biaoQianWeekField
            End Get
            Set
                Me.biaoQianWeekField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserCode() As String
            Get
                Return Me.userCodeField
            End Get
            Set
                Me.userCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class DelFQCModel
        
        Private userCodeField As String
        
        Private sPCNOField As String
        
        '''<remarks/>
        Public Property UserCode() As String
            Get
                Return Me.userCodeField
            End Get
            Set
                Me.userCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SPCNO() As String
            Get
                Return Me.sPCNOField
            End Get
            Set
                Me.sPCNOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendFQCResultModel
        
        Private sPCNOField As String
        
        '''<remarks/>
        Public Property SPCNO() As String
            Get
                Return Me.sPCNOField
            End Get
            Set
                Me.sPCNOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(BizResultOfSendFQCResultModel)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BizResult
        
        Private codeField As String
        
        Private messageField As String
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Message() As String
            Get
                Return Me.messageField
            End Get
            Set
                Me.messageField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BizResultOfSendFQCResultModel
        Inherits BizResult
        
        Private resultField As SendFQCResultModel
        
        '''<remarks/>
        Public Property Result() As SendFQCResultModel
            Get
                Return Me.resultField
            End Get
            Set
                Me.resultField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub SendFQCCompletedEventHandler(ByVal sender As Object, ByVal e As SendFQCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendFQCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BizResultOfSendFQCResultModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BizResultOfSendFQCResultModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub SendSubFQCCompletedEventHandler(ByVal sender As Object, ByVal e As SendSubFQCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendSubFQCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BizResultOfSendFQCResultModel
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BizResultOfSendFQCResultModel)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")>  _
    Public Delegate Sub DelFQCCompletedEventHandler(ByVal sender As Object, ByVal e As DelFQCCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DelFQCCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BizResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BizResult)
            End Get
        End Property
    End Class
End Namespace
