CREATE OR REPLACE TYPE super_t AS OBJECT
(n NUMBER, MEMBER FUNCTION func RETURN NUMBER) NOT final;

CREATE OR REPLACE TYPE BODY super_t AS
MEMBER FUNCTION func RETURN NUMBER IS BEGIN RETURN 1; END; END;

CREATE TYPE sub_t UNDER super_t
(n2 NUMBER,
OVERRIDING MEMBER FUNCTION func RETURN NUMBER) NOT final;

CREATE OR REPLACE TYPE BODY sub_t AS
OVERRIDING MEMBER FUNCTION func RETURN NUMBER IS BEGIN RETURN 2; END; 
END;

CREATE OR REPLACE TYPE final_t UNDER sub_t
(n3 NUMBER);

DECLARE
v0 super_t := super_t(2021);
v1 sub_t := sub_t(1,2);
v2 final_t := final_t(1,2,3);
BEGIN
DBMS_OUTPUT.PUT_LINE('answer:'|| v0.func); 
DBMS_OUTPUT.PUT_LINE('answer:'|| v1.func); 
DBMS_OUTPUT.PUT_LINE('answer:'|| v2.func); 
END;