'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.18063
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'此类是由 StronglyTypedResourceBuilder
'类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
'若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
'(以 /str 作为命令选项)，或重新生成 VS 项目。
'''<summary>
'''  一个强类型的资源类，用于查找本地化的字符串等。
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class FrmSnTrackQuery
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  返回此类使用的缓存的 ResourceManager 实例。
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BasicFind.FrmSnTrackQuery", GetType(FrmSnTrackQuery).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  使用此强类型资源类，为所有资源查找
    '''  重写当前线程的 CurrentUICulture 属性。
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column1_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column1.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column10_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column10.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column11_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column11.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column12_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column12.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column2_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column2.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column3_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column3.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column4_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column4.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column5_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column5.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column6_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column6.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column7_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column7.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column8_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column8.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 True 的 System.Boolean 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property Column9_UserAddedColumn() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Column9.UserAddedColumn", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 {X=252,Y=12} 的 System.Drawing.Point 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property ContextMenuStrip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("ContextMenuStrip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 {X=377,Y=50} 的 System.Drawing.Point 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property menuStrip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("menuStrip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 {X=44,Y=10} 的 System.Drawing.Point 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property StatusStrip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("StatusStrip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
    
    '''<summary>
    '''  查找 System.Drawing.Bitmap 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property ToolExcel_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ToolExcel.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  查找 System.Drawing.Bitmap 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property ToolExit_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ToolExit.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  查找 System.Drawing.Bitmap 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property ToolReflsh_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("ToolReflsh.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  查找类似于 {X=150,Y=12} 的 System.Drawing.Point 类型的本地化资源。
    '''</summary>
    Friend Shared ReadOnly Property ToolStrip1_TrayLocation() As System.Drawing.Point
        Get
            Dim obj As Object = ResourceManager.GetObject("ToolStrip1.TrayLocation", resourceCulture)
            Return CType(obj,System.Drawing.Point)
        End Get
    End Property
End Class
