










-- =========================================
-- RunCard V1.0.0.4 , 2015/06/08
-- =========================================
-- MESDB
-- Table: m_RuncardProcessParamterStandard_t, Add WirePartNumber2,3,4
ALTER  TABLE DBO.M_RUNCARDPROCESSPARAMTERSTANDARD_T ADD 
WIREPARTNUMBERTWO NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDPROCESSPARAMTERSTANDARD_T ADD 
WIREPARTNUMBERTHREE NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDPROCESSPARAMTERSTANDARD_T ADD 
WIREPARTNUMBERFOUR NVARCHAR(100)

--Table: m_RunCardUploadProcessParamterStandard_t, Add WirePartNumber2,3,4
ALTER  TABLE DBO.M_RUNCARDUPLOADPROCESSPARAMTERSTANDARD_T ADD 
WIREPARTNUMBERTWO NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDUPLOADPROCESSPARAMTERSTANDARD_T ADD 
WIREPARTNUMBERTHREE NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDUPLOADPROCESSPARAMTERSTANDARD_T ADD 
WIREPARTNUMBERFOUR NVARCHAR(100)
 
--Table: m_RunCardDetailCheckItem_t, Add RightLinePartNumber2,3,4,LeftLinePartNumber2,3,4
ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
RIGHTLINEPARTNUMBERTWO NVARCHAR(50)

ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
RIGHTLINEPARTNUMBERTHREE NVARCHAR(50)

ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
RIGHTLINEPARTNUMBERFOUR NVARCHAR(50)
 
ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
LEFTLINEPARTNUMBERTWO NVARCHAR(50)

ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
LEFTLINEPARTNUMBERTHREE NVARCHAR(50)

ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
LEFTLINEPARTNUMBERFOUR NVARCHAR(50)

-- Table: m_RuncardUploadProcessParamterStandard_t, Add WireDescription2,3,4
ALTER  TABLE DBO.M_RUNCARDUPLOADPROCESSPARAMTERSTANDARD_T ADD 
WireDescriptionTwo NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDUPLOADPROCESSPARAMTERSTANDARD_T ADD 
WireDescriptionThree NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDUPLOADPROCESSPARAMTERSTANDARD_T ADD 
WireDescriptionFour NVARCHAR(100)

-- Table: m_RuncardProcessParamterStandard_t, add WireDescription2,3,4
ALTER  TABLE DBO.M_RUNCARDPROCESSPARAMTERSTANDARD_T ADD 
WireDescriptionTwo NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDPROCESSPARAMTERSTANDARD_T ADD 
WireDescriptionThree NVARCHAR(100)

ALTER  TABLE DBO.M_RUNCARDPROCESSPARAMTERSTANDARD_T ADD 
WireDescriptionFour NVARCHAR(100)

------------------
ALTER TABLE DBO.M_RUNCARDALLOWANCEPARAMETER_T ADD
ToleranceRange NVARCHAR(20)

ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
LEFTCUTSIZE NVARCHAR(20)

ALTER TABLE DBO.M_RUNCARDDETAILCHECKITEM_T ADD
RIGHTCUTSIZE NVARCHAR(20)

UPDATE M_RUNCARDDETAILCHECKITEM_T SET LEFTCUTSIZE='-0',
RIGHTCUTSIZE='-0'


 create unique nonclustered index IX_RuncardProcessParamterStandard 
 on M_RUNCARDPROCESSPARAMTERSTANDARD_T (TVPartNumber,WirePartNumber,WIREPARTNUMBERTWO
,WIREPARTNUMBERTHREE,WIREPARTNUMBERFOUR) 


alter table M_RUNCARDDETAILCHECKITEM_T
add Tolerance nvarchar(40),ToleranceRange nvarchar(40)

 select tolerance, * from DBO.M_RUNCARDALLOWANCEPARAMETER_T 

-- =========================================
-- RunCard V1.0.0.1 , 2015/05/13
-- =========================================
-- MESDB 
alter table M_RUNCARDALLOWANCEPARAMETER_T
add  Tolerance nvarchar(20)

alter table M_RUNCARDALLOWANCEPARAMETERUPLOAD_T
add  Tolerance nvarchar(20)

