//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Multilingual {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Multilingual.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string MesSystem_Login_btnClose {
            get {
                return ResourceManager.GetString("MesSystem_Login_btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登录.
        /// </summary>
        public static string MesSystem_Login_btnLogin {
            get {
                return ResourceManager.GetString("MesSystem_Login_btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 连接SAP数据源.
        /// </summary>
        public static string MesSystem_Login_chkSap {
            get {
                return ResourceManager.GetString("MesSystem_Login_chkSap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 立讯精密工业股份有限公司          版权所有.
        /// </summary>
        public static string MesSystem_Login_lblbtitle {
            get {
                return ResourceManager.GetString("MesSystem_Login_lblbtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司代码:.
        /// </summary>
        public static string MesSystem_Login_lblFactory {
            get {
                return ResourceManager.GetString("MesSystem_Login_lblFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言:.
        /// </summary>
        public static string MesSystem_Login_lblLang {
            get {
                return ResourceManager.GetString("MesSystem_Login_lblLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工厂代码:.
        /// </summary>
        public static string MesSystem_Login_lblProfit {
            get {
                return ResourceManager.GetString("MesSystem_Login_lblProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码:.
        /// </summary>
        public static string MesSystem_Login_lblPwd {
            get {
                return ResourceManager.GetString("MesSystem_Login_lblPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名:.
        /// </summary>
        public static string MesSystem_Login_lblUser {
            get {
                return ResourceManager.GetString("MesSystem_Login_lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码不正确.
        /// </summary>
        public static string MesSystem_Login_PasswordError {
            get {
                return ResourceManager.GetString("MesSystem_Login_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 该用户不存在或者没有MES系统权限.....
        /// </summary>
        public static string MesSystem_Login_UserNotExists {
            get {
                return ResourceManager.GetString("MesSystem_Login_UserNotExists", resourceCulture);
            }
        }
    }
}
