'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace DcsWebReference
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WorkStationSoapBinding", [Namespace]:="http://elearning.luxshare-ict.com/axis/WorkStation.jws")>  _
    Partial Public Class WorkStationService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getLicenceCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertPersonOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.RCard.My.MySettings.Default.RCard_DcsWebReference_WorkStationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getLicenceCodeCompleted As getLicenceCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event insertPersonCompleted As insertPersonCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://elearning.luxshare-ict.com/axis/WorkStation.jws")>  _
        Public Function getLicenceCode(ByVal jobnumber As String, ByVal stationCode As String) As <System.Xml.Serialization.SoapElementAttribute("getLicenceCodeReturn")> Integer
            Dim results() As Object = Me.Invoke("getLicenceCode", New Object() {jobnumber, stationCode})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getLicenceCodeAsync(ByVal jobnumber As String, ByVal stationCode As String)
            Me.getLicenceCodeAsync(jobnumber, stationCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getLicenceCodeAsync(ByVal jobnumber As String, ByVal stationCode As String, ByVal userState As Object)
            If (Me.getLicenceCodeOperationCompleted Is Nothing) Then
                Me.getLicenceCodeOperationCompleted = AddressOf Me.OngetLicenceCodeOperationCompleted
            End If
            Me.InvokeAsync("getLicenceCode", New Object() {jobnumber, stationCode}, Me.getLicenceCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OngetLicenceCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.getLicenceCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getLicenceCodeCompleted(Me, New getLicenceCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://DefaultNamespace", ResponseNamespace:="http://elearning.luxshare-ict.com/axis/WorkStation.jws")>  _
        Public Function insertPerson(ByVal name As String, ByVal age As Integer, ByVal address As String) As <System.Xml.Serialization.SoapElementAttribute("insertPersonReturn")> Integer
            Dim results() As Object = Me.Invoke("insertPerson", New Object() {name, age, address})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertPersonAsync(ByVal name As String, ByVal age As Integer, ByVal address As String)
            Me.insertPersonAsync(name, age, address, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertPersonAsync(ByVal name As String, ByVal age As Integer, ByVal address As String, ByVal userState As Object)
            If (Me.insertPersonOperationCompleted Is Nothing) Then
                Me.insertPersonOperationCompleted = AddressOf Me.OninsertPersonOperationCompleted
            End If
            Me.InvokeAsync("insertPerson", New Object() {name, age, address}, Me.insertPersonOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertPersonOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertPersonCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertPersonCompleted(Me, New insertPersonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getLicenceCodeCompletedEventHandler(ByVal sender As Object, ByVal e As getLicenceCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getLicenceCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub insertPersonCompletedEventHandler(ByVal sender As Object, ByVal e As insertPersonCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertPersonCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
End Namespace
